---
title: "About me"
---



ADD SOME INFO HERE




ACADEMIC WORK EXPERIENCE 

December 2024 – ongoing
Post-doctoral researcher
Institut de Ciències del Mar (ICM-CSIC), Barcelona, Spain
Supervisor: Dr Francisco Ramírez & Dr Maria Grazia Penino
Project: Spatial Habitat Identification and Forecasting Tool (SHIFT)

April 2023 – Oct 2024
Post-doctoral researcher
Institut de Ciències del Mar (ICM-CSIC), Barcelona, Spain
Supervisor: Dr Francisco Ramírez
Project: A Safe Operating Space for Penguins: fostering the present and future conservation of penguins and their associated marine systems (SOSPEN)

April 2021 – June 2022	
Post-doctoral researcher
Centre d'Etudes Biologiques de Chizé (CEBC-CNRS), France
Supervisor: Dr Yan Ropert-Coudert
Project: Do Adélie penguins care about boundaries? Using the winter locations of a sentinel species for dynamic management of Marine Protected Areas under climate change scenarios
Funded by Make Our Planet Great Again grant and WWF-UK

October 2020 – March 2021	
Post-doctoral researcher
Department of Animal Ecology, Netherlands Institute of Ecology (NIOO-KNAW), Wageningen, Netherlands
Supervisors: Dr Marcel Visser & Dr Antica Culina
Project: SPI-Birds - Studies of Populations of Individuals Birds Network &	Database

October 2014 – October 2016	
Pre-doctoral researcher
Department of Evolutive biology, Ecology and Environmental science
University of Barcelona, Spain

NON-ACADEMIC WORK EXPERIENCE 

October 2018 – July 2020
Data Scientist
Proyectos en Gestión del Conocimiento, Mataró, Spain
Project: SAPIENS, Funded by FECYT/CDTI Spain 
