---
title: "Awards"
---

### Project Grants

*Make Our Planet Great Again*, Post-doctoral grant, France, Dec 2020

### Fellowships

[SCAR Ant-ICON CCAMLR Fellowship, 2025](https://scar.org/members/zajkova-2025)

### Travel grants

Travel grant, Antarctic Essential Biodiversity Variables Workshop, Cambridge, UK, Sep 2024	   
Diversity Scholarship, IEEE Vis 2019 Conference, Vancouver, Canada (declined), 	Oct 2019	    
Diversity Scholarship, IEEE Vis 2018 Conference, Berlin, Germany, Oct 2018	   
Diversity Scholarship, OpenVis 2018 Conference, Paris, France, May 2018	     
Travel grant, Lorentz Center Leiden, Netherlands, Aug 2017      
Travel grant, Montcelimar Foundation & UB, Spain, Dec 2016	    
Internship Travel Award APIF, UB, Spain, Oct 2015     
Travel Award, Seabird Group Conference, UK, March 2014	    
Travel Award, Waterbird Society Conference, Germany, Sep 2013	    

### Scholarships

PhD. scholarship - APIF, University of Barcelona, Spain, Oct 2012 - Oct 2016	    
Master scholarship, Ministry of Education, Spain, 2011 – 2012	    
Centre of documentation of plant biodiversity scholarship, University of Barcelona, Spain, 2011 – 2012	       
Summer course scholarship "Conservation Biology summer school", University of Zaragoza, Spain, July 2011	     
Academic Excellence Scholarship, Univ. of Constantine Phil. Nitra, Slovakia, 2005, 2006	          

### Other 

Seal of Excellence of MSCA Post-doctoral grant (project not financed), Feb 2022	   