---
title: "Conferences"
---

I enjoyed presenting my research at multiple national and international conferences. 

Include photo from penuin conf

Talks

11th International Penguin Conference. Chile. September 2023
Zajková, Z., Ropert-Coudert, Y., Chiaradia, A., Seddon, P., Ramírez, F. "Safe Operating Space for Penguins (SOSPEN)” initiative: a global effort towards the IUCN-Penguin Specialist Group vision of "penguins in perpetuity". 

10th SCAR Open Science Conference. Online. August 2022
Zajková, Z., Kato, A., Raclot, T., Angelier, F., Marciau, C., Thiebot, J. B., Ropert-Coudert, Y. Do Adélie penguins care about boundaries? Spatio-temporal consistency in the wintering behaviour of Antarctic sentinel species – implications for conservation.

Annual meeting day of the Marine Predators Team, CEBC-CNRS. Chizé, France. May 2022
Zajková, Z., Kato, A., Raclot, T., Angelier, F., Marciau, C., Thiebot, J. B., Ropert-Coudert, Y. Do Adélie penguins care about boundaries? Spatio-temporal consistency in the wintering behaviour of Antarctic sentinel species – implications for conservation. 

Measuring Behaviour 2018. Manchester, United Kingdom. June 2018
Zajková, Z., Reyes-González, J.M., González-Solís, J., Bartumeus, F. The Movement Ecology of Seabirds revealed with Unsupervised Behavioural Clustering.

I Jornada d’investigadors predoctorals (JIP-CEAB). Blanes, Spain. June 2017
Zajková, Z. Movement ecology in pelagic seabirds.

6th International Albatross and Petrels Conference. Barcelona, Spain. September 2016
Zajková, Z., Riera-Buch, M., Ryan, P.G., González-Solís, J. Giant petrels: a textbook example of sexual segregation in birds.

Aranda L., Militão, T., Zajková, Z., Reyes-González, J.M., Ryan, P.G., González-Solís, J. The trans-equatorial migration of great shearwaters. Talk (presented by LA).

Reyes-González, J.M., Zajková, Z., Ramos, R., González-Solís, J. Multi-year tracking of seabirds as a tool to develop adaptive management strategies: the case of Cory’s shearwaters foraging in the Canary Current. Talk (presented by JMRG).

BOU: Birds in time and space: avian tracking and remote sensing. Leicester, UK. March 2015
Reyes-González, J.M., Zajková, Z., Ramos, R., González-Solís, J. Annual consistency of foraging grounds depends on spatial scale and population/individual level: the case of Cory’s Shearwater in the Canary Current upwelling. Talk (presented by JMRG).

15th National and 12th International Conference of Spanish Ethological Society. Barcelona, Spain. September 2014
Zajková, Z., Guallar, S., González-Solís, J. Individual activity strategies and cycles in a small oceanic seabird.

12th International Conference of Seabird Group. Oxford, UK. March 2014
Zajková, Z., Guallar, S., Militão, T., González-Solís, J. Movements and at-sea activity of Boyd's Shearwaters (Puffinus boydi) using geolocators and stable isotope analysis.

37th Annual meeting of the Waterbird Society. Wilhelmshaven, Germany. September 2013
Zajková, Z., Guallar, S., Militão, T., González-Solís, J. Movements and at-sea activity of Boyd's Shearwaters (Puffinus boydi) using geolocators and stable isotope analysis.

Posters

8th International Bio-logging Conference. Japan. Online. March 2024
Zajková, Z., Ropert-Coudert, Y., Chiaradia, A., Seddon, P., Ramírez, F. "Safe Operating Space for Penguins (SOSPEN): a global bio-logging initiative for penguin conservation".

Zaldúa, N., Zajková, Z., Farías, A., Marciau, C., Machado-Gaye, A.L., Menéndez-Blázquez, J.,  Muñoz, J., Raslan, M., Rozas Sia, M.G., Valdes, A., Vaz-Canosa, P., Ropert-Coudert, Y., Kato, A. & Soutullo, A. Winter migration and isotopic niche of Adélie penguins from Western Antarctic Peninsula: species ecological insights to contribute to marine spatial planning and management.

18th CNFRAA, Toulouse. France. May 2022
Zajková, Z., Kato, A., Raclot, T., Angelier, F., Marciau, C., Thiebot, J. B., Ropert-Coudert, Y. Do Adélie penguins care about boundaries? Spatio-temporal consistency in the wintering behaviour of Antarctic sentinel species – implications for conservation.

1st Meeting of the Iberian Ecological Society & XIV AEET Meeting. Barcelona, Spain. February 2019
Zajková, Z., Reyes-González, J.M., González-Solís, J., Bartumeus, F. The Movement Ecology of Seabirds revealed with Unsupervised Behavioural Clustering.

22th Conference of Spanish Ornithological Society. Madrid, Spain. December 2014
Zajková, Z., Guallar, S., González-Solís, J. New insights into behavioural strategies and time cycles in a small oceanic seabird: Boyd's Shearwater (Puffinus boydi).
Pastor-Prieto, M., Reyes González, J. M., Rivas, M., Zajková, Z., Cuthbert, R., Ryan, P. G., González-Solís, J. Revealing the annual cycle of a highly pelagic seabird from the South Atlantic: Atlantic Petrel (Pterodroma incerta).

5th International Bio-Logging Science Symposium (BLS5). Strasbourg, France. September 2014
Zajková, Z., Guallar, S., González-Solís, J. Individual activity strategies and circadian, circalunar and circannual activity in Boyd's Shearwaters.


Attendence (no contribution)

International Seabird Group Conference, Portugal. September 2024

Congreso Nacional y Iberoamaricano de Etología y Ecología Evolutiva, Badajoz, Spain. November 2023

