---
title: "Publications"
---

### Research articles peer-reviewed published/accepted

Morera‐Pujol, V., Catry, P., Magalhães, M., Péron, C., Reyes‐González, J. M., Granadeiro, J. P., \... & Ramos, R. (2025). Migratory Connectivity and Non‐Breeding Habitat Segregation Across Biogeographical Scales in Closely Related Seabird Taxa. Diversity and Distributions, 31(3), e70013. <https://doi.org/10.1111/ddi.70013>

Zaldúa, N., Zajková, Z., Machado-Gaye, A. L., Franco-Trecu, V., Cosse, M., Ropert-Coudert, Y., Kato, A. & Soutullo, A. (2024). Changing the focus: The need for cross-scale dynamic management in the Southern Ocean and implications for holistic conservation of Antarctic marine living resources. Marine Policy, 170, 106361. <https://doi.org/10.1016/j.marpol.2024.106361>

Morera‐Pujol, V., Catry, P., Magalhães, M., Péron, C., Reyes‐González, J. M., Granadeiro, J. P., ..., Zajková, Z., ... & Ramos, R. (2023). Methods to detect spatial biases in tracking studies caused by differential representativeness of individuals, populations and time. Diversity and Distributions, 29, 19--38. <https://doi.org/10.1111/ddi.13642>

Halpin, L. R., Ross, J. D., Ramos, R., ..., Zajková, Z., ... & Clarke, R. H. (2021). Double‐tagging scores of seabirds reveals that light‐level geolocator accuracy is limited by species idiosyncrasies and equatorial solar profiles. Methods in Ecology and Evolution, 12(11), 2243-2255. <https://doi.org/10.1111/2041-210X.13698>

Beal, M., Dias, M. P., Phillips, R. A., Oppel, S., Hazin, C., ..., Zajková, Z., Zango, L., & Catry, P. (2021). Global political responsibility for the conservation of albatrosses and large petrels. Science Advances 3;7(10):eabd7225. <https://www.science.org/doi/10.1126/sciadv.abd7225>

Culina, A., Adriaensen, F., Bailey, L. D., Burgess, M. D., Charmantier, A., Cole, E. F., ..., Zajková, Z., ..., & Visser, M. E. (2020). Connecting the data landscape of long‐term ecological studies: the SPI‐Birds data hub. Journal of Animal Ecology, 90(9), 2147-2160. <https://doi.org/10.1111/1365-2656.13388>

Ramos, R., Paiva, V. H., Zajková, Z., Precheur, C., Fagundes, A. I., Jodice, P. G. R., Mackin, W., Zino, F., Bretagnolle, V., González-Solís, J. (2020) Spatial ecology of closely-related taxa: the case of the little shearwater complex in the North Atlantic Ocean. Zoological Journal of the Linnean Society, 191(2), 482-502. <https://doi.org/10.1093/zoolinnean/zlaa045>

Ramos, R., Reyes-González, J. M., Morera-Pujol, V., Zajková, Z., Militão, T., & González-Solís, J. (2020). Disentangling environmental from individual factors in isotopic ecology: A 17-year longitudinal study in a long-lived seabird exploiting the Canary Current. Ecological Indicators, 111, 105963. <https://doi.org/10.1016/j.ecolind.2019.105963>

Pastor-Prieto, M., Ramos, R., Zajková, Z., Reyes-González, J.M., Rivas, M.L., Ryan, P.G., González-Solís, J. (2019). Spatial ecology, phenological variability and moulting patterns of the Endangered Atlantic petrel Pterodroma incerta. Endangered Species Research, 40, 189-206. <https://doi.org/10.3354/esr00991>

Zango, L., Reyes-González, J. M., Militão, T., Zajková, Z., Álvarez-Alonso, E., Ramos, R., & González-Solís, J. (2019). Year-round individual specialization in the feeding ecology of a long-lived seabird. Scientific reports, 9(1), 1-12. <https://doi.org/10.1038/s41598-019-48214-0>

Zajková, Z., Militão, T., González-Solís, J. (2017). Year-round movements of a small seabird and oceanic isotopic gradient in the tropical Atlantic. Mar Ecol Prog Ser 579 169-183. <https://doi.org/10.3354/meps12269>

Becker P. H., Schmaljohann H., Riechert J., Wagenknecht G., Zajková, Z., González-Solís J. (2016). Common Terns on the East Atlantic Flyway: temporal--spatial distribution during the non-breeding period. Journal of Ornithology. <https://doi.org/10.1007/s10336-016-1346-2>

Rodríguez-Ruiz J., de la Puente J., Parejo D., Valera F., Calero-Torralbo M. A., Reyes-González J. M., Zajková, Z., Bermejo A., Avilés J. M. (2014). Disentangling Migratory Routes and Wintering Grounds of Iberian Near-Threatened European Rollers Coracias garrulus. PLoS ONE 9(12): e115615. <https://doi.org/10.1371/journal.pone.0115615>

### Reports

Soutullo, A., Machado-Gaye, A. L., Zajková, Z., Kato, A., Ropert-Coudert, Y. (2022). Adélie penguins of King George Island depend on resources in CCAMLR subarea 48.1 in summer, but subareas 48.5 and 48.2 in winter. Report for the Working Group on Ecosystem Monitoring and Management (WG-EMM-2022/44) of Commission for the Conservation of Antarctic Marine Living Resources (CCAMLR). <https://meetings.ccamlr.org/en/wg-emm-2022/44>

### Books

Reyes-González, J. M., Zajková, Z., Morera-Pujol, V., De Felipe, F., Militão, T., Dell'Ariccia, G., Ramos, R., Igual, J. M., Arcos, J. M. y González-Solís, J. (2017). Migración y ecología espacial de las poblaciones españolas de pardela cenicienta. Monografía nº3 del programa Migra. SEO/BirdLife. Madrid. 153 p. <https://doi.org/10.31170/0056>

### PhD thesis

Zajková, Z. (2020). Movement ecology in pelagic seabirds. University of Barcelona. <https://www.tdx.cat/handle/10803/668688>
